import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ModalProvider } from "@/components/ui/animated-modal";

const quickSand = localFont({
  src: [
    {
      path: './fonts/quickSand-light.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: './fonts/quickSand-regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/quickSand-medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/quickSand-semibold.ttf',
      weight: '600',
      style: 'normal',
    },
    {
      path: './fonts/quickSand-bold.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
   variable: '--font-quick-sand'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${quickSand.variable}`}>
        <ModalProvider>
          {children}
          </ModalProvider>
      </body>
    </html>
  );
}