import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ModalProvider } from "@/components/ui/animated-modal";
import { SessionProvider } from "next-auth/react";
import Providers from "./providers";

const quickSand = localFont({
  src: [
    {
      path: "./fonts/quicksand-light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/quicksand-regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/quicksand-medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/quicksand-semibold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/quicksand-bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-quick-sand",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${quickSand.variable}`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
