import type { Metadata } from "next";

import SideBar from "@/components/dashboard/SideBar";
import NavigationBar from "@/components/NavigationBar";
import { PortfolioProvider } from "@/contexts/PortfolioProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        <PortfolioProvider>
          <NavigationBar />
          <div className="flex">
            <SideBar />
            <main className="flex-1 p-6">{children}</main>
          </div>
        </PortfolioProvider>
      </body>
    </html>
  );
}
